apiVersion: v1
kind: Service
metadata:
  name: eks-project-service
  labels:
    app: eks-project
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: eks-project
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  type: LoadBalancer

      


